version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - dependencies
    open-pull-requests-limit: 10
    rebase-strategy: auto
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - dependencies
    open-pull-requests-limit: 10
    rebase-strategy: auto
    versioning-strategy: increase
